### ISSUE TITLE
#Leetcode TwoSum

### ISSUE THREAD

**Issue by katariarajat** [katariarajat/HactoberFest2021#3]
https://leetcode.com/problems/two-sum/

**Comment by rakeshbodavula** [comment]
I will do it can u assign me this issue @katariarajat

**Comment by katariarajat** [comment]
@rakeshbodavula sure assigned

**Comment by rakeshbodavula** [comment]
> @rakeshbodavula sure assigned

made a PR #17 
please check it out I mentioned 2 approaches, other one is commented
