### ISSUE TITLE
Design a Portfolio 

### ISSUE THREAD

**Issue by katariarajat** [katariarajat/HactoberFest2021#80]
Design a portfolio website template, 
Website must have sections About, Contact, Projects 
*Website should be responsive*
Language HTML, CSS , JAVASCRIPT

**Comment by AravindHari** [comment]
Hey @katariarajat I would like this task

**Comment by harsh6975** [comment]
> @katariarajat adding react based portfolio will increase the complexity of the process. The process of creating and running a react app itself is hectic.

There is nothing about complexity; react provides more and smooths tools.
Also, I don't this there will be an issue in accepting both the projects, So please let's focus on our work.
